server:
  port: 8082

spring:
  application:
    name: video-processor-worker

storage:
  endpoint: ${STORAGE_ENDPOINT:http://localhost:9000}
  access-key: ${STORAGE_ACCESS_KEY:minioadmin}
  secret-key: ${STORAGE_SECRET_KEY:minioadmin}
  bucket: ${STORAGE_BUCKET:videos}

sqs:
  endpoint: ${SQS_ENDPOINT:http://localhost:4566}
  region: ${SQS_REGION:us-east-1}
  access-key: ${SQS_ACCESS_KEY:test}
  secret-key: ${SQS_SECRET_KEY:test}
  video-processing-queue: ${SQS_VIDEO_PROCESSING_QUEUE:video-processing-queue}

sns:
  endpoint: ${SNS_ENDPOINT:http://localhost:4566}
  region: ${SNS_REGION:us-east-1}
  access-key: ${SNS_ACCESS_KEY:test}
  secret-key: ${SNS_SECRET_KEY:test}
  video-completed-topic: ${SNS_VIDEO_COMPLETED_TOPIC:video-completed-topic}

# Actuator - Health checks e Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${JAEGER_TRACING_URL:http://localhost:4318/v1/traces}